services:
  - type: web
    name: vesturo-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install --production
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
